name: tenant_app
description: Production Firebase implementation package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auth_interface:
    path: ../../packages/features/auth/auth_interface

  firebase_auth_impl:
    path: ../../packages/features/auth/firebase_auth_impl

  fake_auth_impl:
    path: ../../packages/features/auth/fake_auth_impl